name: Test Docker Action (External Repo)

on:
  push:
    branches: [ main ]

jobs:
  run-docker-action:
    runs-on: ubuntu-latest
    steps:
      - name: Run docker action from another repo
        uses: i-am-vengatesh/composite-action/.github/actions/hello-docker@main
        with:
          name: "External Repo User"

